
project_id = "nvxeceukxkyqnqztnkep"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[studio]
enabled = true
port = 54323

# Email testing server. Emails sent with the local dev setup are not actually sent - rather, they
# are monitored, and you can view the emails that would have been sent from the web interface.
[inbucket]
enabled = true
port = 54324

[storage]
enabled = true

[auth]
enabled = true

[realtime]
enabled = true

[functions]
[functions.ai-assistant]
[functions.voice-to-text]
[functions.increment-runs]
[functions.increment-total-runs]
[functions.parse-notes]
[functions.process-imazing-sync]
[functions.desktop-auth]
